---
# This role installs nginx http server and configures it.
- name: "Install nfs-utils"
  package:
    name: nfs-utils
    state: present
  
- name: Create a mountable directory if it does not exist
  file:
    path: /mnt/nfs/shares
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'
  
- name: Copy exports file
  template: 
    src: "exports.j2"
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs-server
  
- name: Start the rpcbind service
  service: 
    name: rpcbind
    state: started
    enabled: yes
  
- name: Start the nfs service
  service: 
    name: nfs-server
    state: started
    enabled: yes
  
#- name: permit traffic in public zone for nfs service
#  firewalld:
#    zone: public
#    service: nfs
#    permanent: yes
#    state: enabled
  
#- name: permit traffic in public zone for rpc-bind service
#  firewalld:
#    zone: public
#    service: rpc-bind
#    permanent: yes
#    state: enabled
  
#- name: permit traffic in public zone for mountd service
#  firewalld:
#    zone: public
#    service: mountd
#    permanent: yes
#    state: enabled
  
