---

- name: Initialize the Kubernetes Cluster
  command: kubeadm init --control-plane-endpoint "kringkube.lab.kringen.local:6443" --pod-network-cidr "{{ pod_network }}" --service-cidr "{{ service_network }}" --upload-certs
  register: kubeadm_init
  failed_when: kubeadm_init.rc != 0

- name: Create bootstrap token with kubeadm
  command: kubeadm token create --print-join-command 
  register: kubeadm_join_command

- name: Ensures /home/erik/.kube dir exists
  file: 
    path: /home/erik/.kube
    state: directory

- name: Copy admin.conf to local .kube directory
  copy:
    dest: "/home/erik/.kube/config"
    src: "/etc/kubernetes/admin.conf"
    force: no
    remote_src: yes
    mode: 0660
    owner: erik
    group: erik

- debug: 
    msg: "{{ kubeadm_join_command.stdout }}"

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory

- name: Copy kubernetes config file for kubectl
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: /root/.kube/config

- name: Install the Tigera Operator 
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
  register: tigera_operator_install
  failed_when: tigera_operator_install.rc != 0

- debug:
    msg: "{{ tigera_operator_install.stdout }}"

- name: Copy calico manifest file
  template: 
    src: calico-base.yaml.j2
    dest: $HOME/calico-base.yaml

- name: Install Calico 
  command: kubectl create -f $HOME/calico-base.yaml 
  register: calico_install
  failed_when: calico_install.rc != 0

- debug:
    msg: "{{ calico_install.stdout }}"
  