---
# This role installs HAProxy and configures it.
- name: "Install Bind DNS Server"
  package: 
    name: bind9
    state: present
- name: "Install Bind-Utils"
  package:
    name: bind9utils
    state: present
- name: "Install Bind-Utils"
  package:
    name: dnsutils
    state: present
- name: create zones directory
  file:
    path: /etc/named/zones
    state: directory
- name: Copy named.conf config
  template: 
    src: named.conf.j2
    dest: /etc/named.conf
- name: Copy reverse domain config
  template: 
    src: prefix.db.j2
    dest: /etc/named/zones/{{ prefix }}.db
- name: Copy domain config
  template: 
    src: "domain.db.j2"
    dest: /etc/named/zones/{{ domain }}.db
- name: Copy dns config
  template: 
    src: "named.conf.local.j2"
    dest: /etc/named/named.conf.local
  notify: reload bind
- name: Start the named service
  service: 
    name: named
    state: started
    enabled: yes

# TODO:  For Raspberry Pi, you may need to disable ipv6 resolution by updating /etc/default/named
#  with OPTIONS="-u bind -4"


#- name: permit traffic in public zone for DNS service
#  firewalld:
#    zone: public
#    service: dns
#    permanent: yes
#    state: enabled
#- name: reload firewalld
#  shell: firewall-cmd --reload