#!/bin/sh

cat<<EOF
-------------------------------------------------------------
Warning: This system is restricted to authorized users only.
Unauthorized access, use, misuse or modification of this
system, the data contained herein, or in transit to/from
this system, may constitute a violation of federal, state
and local laws and subject individual(s) to criminal and/or
civil prosecution and penalties. This system and associated
usage is subject to monitoring and security testing.
There is no expectation of privacy.
-------------------------------------------------------------
EOF