---
- name: Add MondoDB repository
  yum_repository:
    name: mongodb-org-4.4
    description: MondoDB Repository Repo
    baseurl: https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Enable and start mongod daemon
  ansible.builtin.service:
    name: mongod
    enabled: true
    state: started