---
- name: Reset cloud init
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Reset cloud-init
    shell: cloud-init clean --logs
    ignore_errors: yes

- name: Kubernetes Node Setup
  hosts: localhost
  connection: local
  become: true
  roles:
  - common
  