---
# Variables for the HAproxy configuration

# HAProxy supports "http" and "tcp". For SSL, SMTP, etc, use "tcp".

# Port on which HAProxy should listen
listenport: 8888

# A name for the proxy daemon, this wil be the suffix in the logs.
daemonname: myapplb

# Balancing Algorithm. Available options:
# roundrobin, source, leastconn, source, uri
# (if persistance is required use, "source")
balance: roundrobin

proxy_services_frontend:
  - service_name: kube-apiserver
    service_comment: |
      #---------------------------------------------------------------------
      # apiserver frontend which proxys to the control plane nodes
      #---------------------------------------------------------------------
    service_port: 6443
    service_protocol: tcp
    service_options: 
      - tcplog
    service_backend: kube-apiserver

proxy_services_backend:
  - service_name: kube-apiserver
    service_comment: |
      #---------------------------------------------------------------------
      # round robin balancing for apiserver
      #---------------------------------------------------------------------
    backend_port: 6443
    service_protocol: tcp
    service_options: 
      - tcplog
    balance: roundrobin
    backend_hosts:
      - 10.0.0.107
      - 10.0.0.108

firewall_rules:
  - port: 8080/tcp
  - port: 9000/tcp

virtual_ip_address: "10.0.0.100"