- name: Start the chrony service
  service: 
    name: chronyd
    state: started
    enabled: yes

- name: ensure warning banner is configured properly
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - motd
    - issue
    - issue.net
- name: Remove cockpit banner
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - /etc/issue.d/cockpit.issue
  - /etc/motd.d/cockpit

- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager

- name: deploy resolv.conf template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager

- name: Add Kubernetes repository 
  yum_repository:
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    name: "kubernetes"
    state: present 
    description: "Kubernetes Repository"
    gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" 
    exclude: "kubelet kubeadm kubectl"

- name: Dump default configuration for containerd
  shell: rpm-ostree install -y kubelet kubeadm kubectl --idempotent