---
- name: setup python for coreos
  hosts: coreos
  become: yes
  gather_facts: False # would fail since Python isn't installed
  tasks:
  - name: Install python
    raw: rpm-ostree install -y python3
    ignore_errors: yes