---
- hosts: kubernetes_control
  tasks:
  - name: Create bootstrap token with kubeadm
    command: kubeadm token create --print-join-command 
    register: kubeadm_join_command
  - debug: 
      msg: "{{ kubeadm_join_command.stdout }}"
  - name: "Add K8S join info to dummy host"
    add_host:
      name:   "K8S_JOIN_HOLDER"
      join_command:  "{{ kubeadm_join_command.stdout }}"
  become: yes

- hosts: kubernetes_workers
  roles:
  - kubernetes-worker-setup
  become: yes