---
- name: setup python for coreos
  hosts: coreos
  become: yes
  gather_facts: False
  # Need to install python first before running any other roles
  tasks:
  - name: Install python
    raw: rpm-ostree install -y python3 --idempotent
    ignore_errors: yes
  - name: Reboot Raw
    raw: reboot
    ignore_errors: yes
  - name: Wait for server to restart
    local_action:
      module: wait_for
        host={{ inventory_hostname }}
        port=22
        delay=60

- name: Apply common configuration to coreos hosts
  gather_facts: True
  become: yes
  hosts: coreos
  roles:
  - coreos-common
  - kubernetes-coreos

# - hosts: proxy
#   roles:
#   - haproxy
#   become: yes

- hosts: kubernetes_control
  roles:
  - kubernetes-control-setup
  become: yes

# - hosts: kubernetes_co-control
#   tasks:
#   - debug: 
#       msg: "{{ hostvars['K8S_JOIN_HOLDER']['join_command'] }}"

  - name: Check if /etc/kubernetes/kubelet.conf already exists
    stat:
      path:  /etc/kubernetes/kubelet.conf
    register: etc_kubelet

  - name: Join {{ ansible_facts['nodename'] }} to the k8s cluster control-plane
    command: "{{ hostvars['K8S_JOIN_HOLDER']['join_command'] }} --control-plane --certificate-key {{ hostvars['K8S_JOIN_HOLDER']['kubeadm_cert_key'] }}"
    when: not etc_kubelet.stat.exists
    register: kubeadm_control_join_output
    become: yes

- hosts: kubernetes_workers
  roles:
  - kubernetes-worker-setup
  become: yes