---
- hosts: virtual_machines
  remote_user: erik
  roles:
  - common
  become: yes
  
- hosts: proxy
  remote_user: erik
  roles:
  - haproxy
  become: yes

- hosts: kubernetes_node
  roles:
  - kubernetes-common
  become: yes

- hosts: kubernetes_control
  roles:
  - kubernetes-control-setup
  become: yes

- hosts: kubernetes_co-control
  tasks:
  - debug: 
    msg: "{{ hostvars['K8S_JOIN_HOLDER']['control_command'] }}"

  - name: Join {{ ansible_facts['nodename'] }} to the k8s cluster control-plane
    command: "{{ hostvars['K8S_JOIN_HOLDER']['control_command'] }}"
    register: kubeadm_control_join_output

  - debug: 
    msg: "{{ kubeadm_control_join_output }}"

- hosts: kubernetes_workers
  roles:
  - kubernetes-worker-setup
  become: yes