---
- name: Get VMs list
  virt:
    command: list_vms
  register: existing_vms
  changed_when: no
  tags: virt
- name: Copy base image to libvirt directory
  copy:
    dest: "{{ libvirt_pool_dir }}/{{ item.vm_name }}.qcow2"
    src: "{{ base_image }}"
    force: no
    remote_src: yes 
    mode: 0660
  register: copy_results
  tags: virt
- name: Configure the image
  command: |
    virt-customize -a {{ base_image_folder }}/{{ item.vm_base_image }} \
    --hostname {{ item.vm_name }}.{{ domain }} \
    --root-password password:{{ vm_root_pass }} \
    --ssh-inject 'root:file:{{ ssh_key }}' \
    --uninstall cloud-init --selinux-relabel
  when: "item.vm_name not in existing_vms.list_vms"
  tags: virt
- name: Resize the image
  command: |
    qemu-img resize {{ libvirt_pool_dir }}/{{ item.vm_name }}.qcow2 +20G
  when: "item.vm_name not in existing_vms.list_vms"
  tags: virt
- name: Backup the image
  command: |
   cp {{ libvirt_pool_dir }}/{{ item.vm_name }}.qcow2 {{ libvirt_pool_dir }}/{{ item.vm_name }}-tmp.qcow2 
  when: "item.vm_name not in existing_vms.list_vms"
  tags: virt
- name: Resize the filesystem
  command: |
    virt-resize --expand /dev/vda3 {{ libvirt_pool_dir }}/{{ item.vm_name }}-tmp.qcow2 {{ libvirt_pool_dir }}/{{ item.vm_name }}.qcow2
  when: "item.vm_name not in existing_vms.list_vms"
  tags: virt
- name: Define vm
  virt:
    command: define
    xml: "{{ lookup('template', 'rhel8-template.xml.j2') }}"
  when: "item.vm_name not in existing_vms.list_vms"
  tags: virt