---
# This role prepares nodes for kubernetes
- name: Turn off swap
  shell: |
    swapoff -a
  tags: kubernetes-common

- name: Disable swap  
  lineinfile:
    path: /etc/fstab
    regexp: '\sswap\s'
    state: absent 
  tags: kubernetes-common

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  tags: kubernetes-common

- name: Load the required kernel modules 
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay
  tags: kubernetes-common

- name: Persist kernel module loading  
  copy:
    dest: /etc/modules-load.d/k8s.conf 
    content: |
      br_netfilter
      overlay
  tags: kubernetes-common

- name: Tune sysctl parameters  in /proc and the sysctl file
  sysctl:
    name: "{{ item }}" 
    value: '1'
    sysctl_set: yes
    state: present
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  tags: kubernetes-common

- name: Add Kubernetes repository 
  yum_repository:
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    name: "Kubernetes"
    state: present 
    description: "Kubernetes Repository"
    gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" 
    exclude: "kubelet kubeadm kubectl"
  tags: kubernetes-common

- name: Add docker-ce repository for containerd 
  yum_repository:
    name: "Docker-CE" 
    description: "Docker CE Stable" 
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/ 
    state: present
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  tags: kubernetes-common

- name: Install required packages (containerd, kubeadmn, kubectl, kubelet) 
  yum:
    name: "{{ packages }}"
    disable_excludes: "Kubernetes"
  vars:
    packages:
    - containerd.io
    - kubeadm
    - kubelet
    - kubectl
    - iproute-tc
  tags: kubernetes-common

- name: Dump default configuration for containerd
  shell: containerd config default > /etc/containerd/config.toml
  tags: kubernetes-common

- name: Configure crictl to use containerd
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
      debug: false
  tags: kubernetes-common

- name: Enable and start the required services (containerd.io, kubelet) 
  systemd:
    name: "{{ item }}" 
    enabled: yes
    state: started
  with_items:
    - containerd
    - kubelet
  tags: kubernetes-common

- name: permit traffic in public zone for services
  firewalld:
    zone: public
    port: "{{ item.port }}"
    permanent: yes
    state: enabled
  loop: "{{ firewall_rules }}"
  tags: kubernetes-common

- name: permit traffic in public zone for services
  firewalld:
    zone: public
    service: "{{ item.service }}"
    permanent: yes
    state: enabled
  loop: "{{ firewall_services }}"
  tags: kubernetes-common

- name: reload firewalld
  shell: firewall-cmd --reload
  tags: kubernetes-common