---
- name: Configure the Control Plane
  hosts: control-plane
  become: true
  tasks:
    - name: init kubeadm
      ansible.builtin.shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint "{{ansible_host}}:6443"

    - name: create ~/.kube directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: "0755"

    - name: copy kubeconfig file
      shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

    - name: set permission on kubeconfig file
      shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: install Weavenet Pod Network add-on
      ansible.builtin.shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    - name: Generate token to join worker nodes to cluster
      ansible.builtin.shell: sudo kubeadm token create --print-join-command
      register: join_node_token
      delegate_to: controlplane

- name: Join Worker Nodes to cluster
  hosts: workers
  become: true
  tasks:
    - name: Save join token command as variable
      ansible.builtin.set_fact:
        join_node: "{{ hostvars['controlplane'].join_node_token.stdout_lines[0] }}"

    - name: add worker nodes to cluster
      shell: "sudo {{ join_node }}"